# Generated by Django 5.2.10 on 2026-01-11 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lignelivraison_produit_alter_lignelivraison_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livraison',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='livreur',
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_livraison',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livraison',
            name='grossiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(default='PREPARATION', max_length=20),
        ),
    ]
