# Generated by Django 5.2.10 on 2026-01-11 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_utilisateur_adresse_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_livreur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='grossiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_grossiste', to=settings.AUTH_USER_MODEL),
        ),
    ]
