# Generated by Django 5.2.10 on 2026-01-12 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_livraison_livreur_alter_livraison_grossiste'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date'], 'verbose_name': 'mouvement de stock', 'verbose_name_plural': 'mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenoms',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Informations complémentaires sur le mouvement', null=True, verbose_name='commentaire'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="date d'inscription"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='localisation',
            field=models.CharField(blank=True, help_text='Coordonnées GPS ou adresse précise', max_length=255, verbose_name='localisation GPS'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='nom de famille'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure du mouvement', verbose_name='date et heure'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='destination_emplacement',
            field=models.ForeignKey(blank=True, help_text="Emplacement d'arrivée du produit (vide pour les sorties)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_entrants', to='core.emplacement', verbose_name='emplacement de destination'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='core.lot', verbose_name='lot concerné'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.FloatField(help_text='Quantité déplacée (en kg)', verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='source_emplacement',
            field=models.ForeignKey(blank=True, help_text='Emplacement de départ du produit (vide pour les entrées)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_sortants', to='core.emplacement', verbose_name='emplacement source'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée en stock'), ('SORTIE', 'Sortie de stock'), ('TRANSFERT', 'Transfert entre emplacements')], help_text="Type d'opération effectuée sur le stock", max_length=20, verbose_name='type de mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(help_text="Utilisateur ayant effectué l'opération", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_stock', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='compte actif'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, default='Lome', verbose_name='adresse complète'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role', verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='00000000', help_text='Format: +225XXXXXXXX', max_length=20, verbose_name='téléphone'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['-date'], name='idx_mouvement_date'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type_mouvement'], name='idx_mouvement_type'),
        ),
    ]
