# Generated by Django 5.2.10 on 2026-01-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mouvementstock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='derniere_connexion',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='inconnu@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='localisation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
